// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Admins is the predicate function for admins builders.
type Admins func(*sql.Selector)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// ProductBrands is the predicate function for productbrands builders.
type ProductBrands func(*sql.Selector)

// ProductCategories is the predicate function for productcategories builders.
type ProductCategories func(*sql.Selector)

// ProductColors is the predicate function for productcolors builders.
type ProductColors func(*sql.Selector)

// ProductSizes is the predicate function for productsizes builders.
type ProductSizes func(*sql.Selector)

// ProductStock is the predicate function for productstock builders.
type ProductStock func(*sql.Selector)

// Products is the predicate function for products builders.
type Products func(*sql.Selector)

// Reviews is the predicate function for reviews builders.
type Reviews func(*sql.Selector)

// Shops is the predicate function for shops builders.
type Shops func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
