version: "3"
services: 
  app:
    build: 
      context: .
      dockerfile: ./build/go/Dockerfile
    container_name: app
    tty: true
    volumes:
      - ./app:/go/src/app
    env_file:
      - ./app/.env
    networks:
      - golang_test_network
    ports:
      - '8080:8080'

networks:
  golang_test_network:
    external: true