// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/endot1231/ec-backend/ent/predicate"
	"github.com/endot1231/ec-backend/ent/productsizes"
)

// ProductSizesUpdate is the builder for updating ProductSizes entities.
type ProductSizesUpdate struct {
	config
	hooks    []Hook
	mutation *ProductSizesMutation
}

// Where appends a list predicates to the ProductSizesUpdate builder.
func (psu *ProductSizesUpdate) Where(ps ...predicate.ProductSizes) *ProductSizesUpdate {
	psu.mutation.Where(ps...)
	return psu
}

// SetType sets the "type" field.
func (psu *ProductSizesUpdate) SetType(s string) *ProductSizesUpdate {
	psu.mutation.SetType(s)
	return psu
}

// SetSize sets the "size" field.
func (psu *ProductSizesUpdate) SetSize(s string) *ProductSizesUpdate {
	psu.mutation.SetSize(s)
	return psu
}

// SetCreatedAt sets the "created_at" field.
func (psu *ProductSizesUpdate) SetCreatedAt(t time.Time) *ProductSizesUpdate {
	psu.mutation.SetCreatedAt(t)
	return psu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (psu *ProductSizesUpdate) SetNillableCreatedAt(t *time.Time) *ProductSizesUpdate {
	if t != nil {
		psu.SetCreatedAt(*t)
	}
	return psu
}

// SetUpdatedAt sets the "updated_at" field.
func (psu *ProductSizesUpdate) SetUpdatedAt(t time.Time) *ProductSizesUpdate {
	psu.mutation.SetUpdatedAt(t)
	return psu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (psu *ProductSizesUpdate) SetNillableUpdatedAt(t *time.Time) *ProductSizesUpdate {
	if t != nil {
		psu.SetUpdatedAt(*t)
	}
	return psu
}

// SetDeletedAt sets the "deleted_at" field.
func (psu *ProductSizesUpdate) SetDeletedAt(t time.Time) *ProductSizesUpdate {
	psu.mutation.SetDeletedAt(t)
	return psu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (psu *ProductSizesUpdate) SetNillableDeletedAt(t *time.Time) *ProductSizesUpdate {
	if t != nil {
		psu.SetDeletedAt(*t)
	}
	return psu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (psu *ProductSizesUpdate) ClearDeletedAt() *ProductSizesUpdate {
	psu.mutation.ClearDeletedAt()
	return psu
}

// Mutation returns the ProductSizesMutation object of the builder.
func (psu *ProductSizesUpdate) Mutation() *ProductSizesMutation {
	return psu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (psu *ProductSizesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, psu.sqlSave, psu.mutation, psu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psu *ProductSizesUpdate) SaveX(ctx context.Context) int {
	affected, err := psu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (psu *ProductSizesUpdate) Exec(ctx context.Context) error {
	_, err := psu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psu *ProductSizesUpdate) ExecX(ctx context.Context) {
	if err := psu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (psu *ProductSizesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(productsizes.Table, productsizes.Columns, sqlgraph.NewFieldSpec(productsizes.FieldID, field.TypeInt))
	if ps := psu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := psu.mutation.GetType(); ok {
		_spec.SetField(productsizes.FieldType, field.TypeString, value)
	}
	if value, ok := psu.mutation.Size(); ok {
		_spec.SetField(productsizes.FieldSize, field.TypeString, value)
	}
	if value, ok := psu.mutation.CreatedAt(); ok {
		_spec.SetField(productsizes.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := psu.mutation.UpdatedAt(); ok {
		_spec.SetField(productsizes.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := psu.mutation.DeletedAt(); ok {
		_spec.SetField(productsizes.FieldDeletedAt, field.TypeTime, value)
	}
	if psu.mutation.DeletedAtCleared() {
		_spec.ClearField(productsizes.FieldDeletedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, psu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productsizes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	psu.mutation.done = true
	return n, nil
}

// ProductSizesUpdateOne is the builder for updating a single ProductSizes entity.
type ProductSizesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductSizesMutation
}

// SetType sets the "type" field.
func (psuo *ProductSizesUpdateOne) SetType(s string) *ProductSizesUpdateOne {
	psuo.mutation.SetType(s)
	return psuo
}

// SetSize sets the "size" field.
func (psuo *ProductSizesUpdateOne) SetSize(s string) *ProductSizesUpdateOne {
	psuo.mutation.SetSize(s)
	return psuo
}

// SetCreatedAt sets the "created_at" field.
func (psuo *ProductSizesUpdateOne) SetCreatedAt(t time.Time) *ProductSizesUpdateOne {
	psuo.mutation.SetCreatedAt(t)
	return psuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (psuo *ProductSizesUpdateOne) SetNillableCreatedAt(t *time.Time) *ProductSizesUpdateOne {
	if t != nil {
		psuo.SetCreatedAt(*t)
	}
	return psuo
}

// SetUpdatedAt sets the "updated_at" field.
func (psuo *ProductSizesUpdateOne) SetUpdatedAt(t time.Time) *ProductSizesUpdateOne {
	psuo.mutation.SetUpdatedAt(t)
	return psuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (psuo *ProductSizesUpdateOne) SetNillableUpdatedAt(t *time.Time) *ProductSizesUpdateOne {
	if t != nil {
		psuo.SetUpdatedAt(*t)
	}
	return psuo
}

// SetDeletedAt sets the "deleted_at" field.
func (psuo *ProductSizesUpdateOne) SetDeletedAt(t time.Time) *ProductSizesUpdateOne {
	psuo.mutation.SetDeletedAt(t)
	return psuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (psuo *ProductSizesUpdateOne) SetNillableDeletedAt(t *time.Time) *ProductSizesUpdateOne {
	if t != nil {
		psuo.SetDeletedAt(*t)
	}
	return psuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (psuo *ProductSizesUpdateOne) ClearDeletedAt() *ProductSizesUpdateOne {
	psuo.mutation.ClearDeletedAt()
	return psuo
}

// Mutation returns the ProductSizesMutation object of the builder.
func (psuo *ProductSizesUpdateOne) Mutation() *ProductSizesMutation {
	return psuo.mutation
}

// Where appends a list predicates to the ProductSizesUpdate builder.
func (psuo *ProductSizesUpdateOne) Where(ps ...predicate.ProductSizes) *ProductSizesUpdateOne {
	psuo.mutation.Where(ps...)
	return psuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (psuo *ProductSizesUpdateOne) Select(field string, fields ...string) *ProductSizesUpdateOne {
	psuo.fields = append([]string{field}, fields...)
	return psuo
}

// Save executes the query and returns the updated ProductSizes entity.
func (psuo *ProductSizesUpdateOne) Save(ctx context.Context) (*ProductSizes, error) {
	return withHooks(ctx, psuo.sqlSave, psuo.mutation, psuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psuo *ProductSizesUpdateOne) SaveX(ctx context.Context) *ProductSizes {
	node, err := psuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (psuo *ProductSizesUpdateOne) Exec(ctx context.Context) error {
	_, err := psuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psuo *ProductSizesUpdateOne) ExecX(ctx context.Context) {
	if err := psuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (psuo *ProductSizesUpdateOne) sqlSave(ctx context.Context) (_node *ProductSizes, err error) {
	_spec := sqlgraph.NewUpdateSpec(productsizes.Table, productsizes.Columns, sqlgraph.NewFieldSpec(productsizes.FieldID, field.TypeInt))
	id, ok := psuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProductSizes.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := psuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productsizes.FieldID)
		for _, f := range fields {
			if !productsizes.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != productsizes.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := psuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := psuo.mutation.GetType(); ok {
		_spec.SetField(productsizes.FieldType, field.TypeString, value)
	}
	if value, ok := psuo.mutation.Size(); ok {
		_spec.SetField(productsizes.FieldSize, field.TypeString, value)
	}
	if value, ok := psuo.mutation.CreatedAt(); ok {
		_spec.SetField(productsizes.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := psuo.mutation.UpdatedAt(); ok {
		_spec.SetField(productsizes.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := psuo.mutation.DeletedAt(); ok {
		_spec.SetField(productsizes.FieldDeletedAt, field.TypeTime, value)
	}
	if psuo.mutation.DeletedAtCleared() {
		_spec.ClearField(productsizes.FieldDeletedAt, field.TypeTime)
	}
	_node = &ProductSizes{config: psuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, psuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productsizes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	psuo.mutation.done = true
	return _node, nil
}
