// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/endot1231/ec-backend/ent/productcolors"
)

// ProductColorsCreate is the builder for creating a ProductColors entity.
type ProductColorsCreate struct {
	config
	mutation *ProductColorsMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pcc *ProductColorsCreate) SetName(s string) *ProductColorsCreate {
	pcc.mutation.SetName(s)
	return pcc
}

// SetCreatedAt sets the "created_at" field.
func (pcc *ProductColorsCreate) SetCreatedAt(t time.Time) *ProductColorsCreate {
	pcc.mutation.SetCreatedAt(t)
	return pcc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pcc *ProductColorsCreate) SetNillableCreatedAt(t *time.Time) *ProductColorsCreate {
	if t != nil {
		pcc.SetCreatedAt(*t)
	}
	return pcc
}

// SetUpdatedAt sets the "updated_at" field.
func (pcc *ProductColorsCreate) SetUpdatedAt(t time.Time) *ProductColorsCreate {
	pcc.mutation.SetUpdatedAt(t)
	return pcc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pcc *ProductColorsCreate) SetNillableUpdatedAt(t *time.Time) *ProductColorsCreate {
	if t != nil {
		pcc.SetUpdatedAt(*t)
	}
	return pcc
}

// SetDeletedAt sets the "deleted_at" field.
func (pcc *ProductColorsCreate) SetDeletedAt(t time.Time) *ProductColorsCreate {
	pcc.mutation.SetDeletedAt(t)
	return pcc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pcc *ProductColorsCreate) SetNillableDeletedAt(t *time.Time) *ProductColorsCreate {
	if t != nil {
		pcc.SetDeletedAt(*t)
	}
	return pcc
}

// Mutation returns the ProductColorsMutation object of the builder.
func (pcc *ProductColorsCreate) Mutation() *ProductColorsMutation {
	return pcc.mutation
}

// Save creates the ProductColors in the database.
func (pcc *ProductColorsCreate) Save(ctx context.Context) (*ProductColors, error) {
	pcc.defaults()
	return withHooks(ctx, pcc.sqlSave, pcc.mutation, pcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pcc *ProductColorsCreate) SaveX(ctx context.Context) *ProductColors {
	v, err := pcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcc *ProductColorsCreate) Exec(ctx context.Context) error {
	_, err := pcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcc *ProductColorsCreate) ExecX(ctx context.Context) {
	if err := pcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pcc *ProductColorsCreate) defaults() {
	if _, ok := pcc.mutation.CreatedAt(); !ok {
		v := productcolors.DefaultCreatedAt
		pcc.mutation.SetCreatedAt(v)
	}
	if _, ok := pcc.mutation.UpdatedAt(); !ok {
		v := productcolors.DefaultUpdatedAt
		pcc.mutation.SetUpdatedAt(v)
	}
	if _, ok := pcc.mutation.DeletedAt(); !ok {
		v := productcolors.DefaultDeletedAt
		pcc.mutation.SetDeletedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pcc *ProductColorsCreate) check() error {
	if _, ok := pcc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProductColors.name"`)}
	}
	if _, ok := pcc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProductColors.created_at"`)}
	}
	if _, ok := pcc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProductColors.updated_at"`)}
	}
	return nil
}

func (pcc *ProductColorsCreate) sqlSave(ctx context.Context) (*ProductColors, error) {
	if err := pcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pcc.mutation.id = &_node.ID
	pcc.mutation.done = true
	return _node, nil
}

func (pcc *ProductColorsCreate) createSpec() (*ProductColors, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductColors{config: pcc.config}
		_spec = sqlgraph.NewCreateSpec(productcolors.Table, sqlgraph.NewFieldSpec(productcolors.FieldID, field.TypeInt))
	)
	if value, ok := pcc.mutation.Name(); ok {
		_spec.SetField(productcolors.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pcc.mutation.CreatedAt(); ok {
		_spec.SetField(productcolors.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pcc.mutation.UpdatedAt(); ok {
		_spec.SetField(productcolors.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := pcc.mutation.DeletedAt(); ok {
		_spec.SetField(productcolors.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	return _node, _spec
}

// ProductColorsCreateBulk is the builder for creating many ProductColors entities in bulk.
type ProductColorsCreateBulk struct {
	config
	builders []*ProductColorsCreate
}

// Save creates the ProductColors entities in the database.
func (pccb *ProductColorsCreateBulk) Save(ctx context.Context) ([]*ProductColors, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pccb.builders))
	nodes := make([]*ProductColors, len(pccb.builders))
	mutators := make([]Mutator, len(pccb.builders))
	for i := range pccb.builders {
		func(i int, root context.Context) {
			builder := pccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductColorsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pccb *ProductColorsCreateBulk) SaveX(ctx context.Context) []*ProductColors {
	v, err := pccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pccb *ProductColorsCreateBulk) Exec(ctx context.Context) error {
	_, err := pccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pccb *ProductColorsCreateBulk) ExecX(ctx context.Context) {
	if err := pccb.Exec(ctx); err != nil {
		panic(err)
	}
}
