// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/endot1231/ec-backend/ent/predicate"
	"github.com/endot1231/ec-backend/ent/productcategories"
)

// ProductCategoriesDelete is the builder for deleting a ProductCategories entity.
type ProductCategoriesDelete struct {
	config
	hooks    []Hook
	mutation *ProductCategoriesMutation
}

// Where appends a list predicates to the ProductCategoriesDelete builder.
func (pcd *ProductCategoriesDelete) Where(ps ...predicate.ProductCategories) *ProductCategoriesDelete {
	pcd.mutation.Where(ps...)
	return pcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pcd *ProductCategoriesDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pcd.sqlExec, pcd.mutation, pcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pcd *ProductCategoriesDelete) ExecX(ctx context.Context) int {
	n, err := pcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pcd *ProductCategoriesDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(productcategories.Table, sqlgraph.NewFieldSpec(productcategories.FieldID, field.TypeInt))
	if ps := pcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pcd.mutation.done = true
	return affected, err
}

// ProductCategoriesDeleteOne is the builder for deleting a single ProductCategories entity.
type ProductCategoriesDeleteOne struct {
	pcd *ProductCategoriesDelete
}

// Where appends a list predicates to the ProductCategoriesDelete builder.
func (pcdo *ProductCategoriesDeleteOne) Where(ps ...predicate.ProductCategories) *ProductCategoriesDeleteOne {
	pcdo.pcd.mutation.Where(ps...)
	return pcdo
}

// Exec executes the deletion query.
func (pcdo *ProductCategoriesDeleteOne) Exec(ctx context.Context) error {
	n, err := pcdo.pcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productcategories.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pcdo *ProductCategoriesDeleteOne) ExecX(ctx context.Context) {
	if err := pcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
