// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/endot1231/ec-backend/ent/predicate"
	"github.com/endot1231/ec-backend/ent/productbrands"
)

// ProductBrandsQuery is the builder for querying ProductBrands entities.
type ProductBrandsQuery struct {
	config
	ctx        *QueryContext
	order      []productbrands.OrderOption
	inters     []Interceptor
	predicates []predicate.ProductBrands
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductBrandsQuery builder.
func (pbq *ProductBrandsQuery) Where(ps ...predicate.ProductBrands) *ProductBrandsQuery {
	pbq.predicates = append(pbq.predicates, ps...)
	return pbq
}

// Limit the number of records to be returned by this query.
func (pbq *ProductBrandsQuery) Limit(limit int) *ProductBrandsQuery {
	pbq.ctx.Limit = &limit
	return pbq
}

// Offset to start from.
func (pbq *ProductBrandsQuery) Offset(offset int) *ProductBrandsQuery {
	pbq.ctx.Offset = &offset
	return pbq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pbq *ProductBrandsQuery) Unique(unique bool) *ProductBrandsQuery {
	pbq.ctx.Unique = &unique
	return pbq
}

// Order specifies how the records should be ordered.
func (pbq *ProductBrandsQuery) Order(o ...productbrands.OrderOption) *ProductBrandsQuery {
	pbq.order = append(pbq.order, o...)
	return pbq
}

// First returns the first ProductBrands entity from the query.
// Returns a *NotFoundError when no ProductBrands was found.
func (pbq *ProductBrandsQuery) First(ctx context.Context) (*ProductBrands, error) {
	nodes, err := pbq.Limit(1).All(setContextOp(ctx, pbq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{productbrands.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pbq *ProductBrandsQuery) FirstX(ctx context.Context) *ProductBrands {
	node, err := pbq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProductBrands ID from the query.
// Returns a *NotFoundError when no ProductBrands ID was found.
func (pbq *ProductBrandsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pbq.Limit(1).IDs(setContextOp(ctx, pbq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{productbrands.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pbq *ProductBrandsQuery) FirstIDX(ctx context.Context) int {
	id, err := pbq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProductBrands entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProductBrands entity is found.
// Returns a *NotFoundError when no ProductBrands entities are found.
func (pbq *ProductBrandsQuery) Only(ctx context.Context) (*ProductBrands, error) {
	nodes, err := pbq.Limit(2).All(setContextOp(ctx, pbq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{productbrands.Label}
	default:
		return nil, &NotSingularError{productbrands.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pbq *ProductBrandsQuery) OnlyX(ctx context.Context) *ProductBrands {
	node, err := pbq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProductBrands ID in the query.
// Returns a *NotSingularError when more than one ProductBrands ID is found.
// Returns a *NotFoundError when no entities are found.
func (pbq *ProductBrandsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pbq.Limit(2).IDs(setContextOp(ctx, pbq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{productbrands.Label}
	default:
		err = &NotSingularError{productbrands.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pbq *ProductBrandsQuery) OnlyIDX(ctx context.Context) int {
	id, err := pbq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProductBrandsSlice.
func (pbq *ProductBrandsQuery) All(ctx context.Context) ([]*ProductBrands, error) {
	ctx = setContextOp(ctx, pbq.ctx, "All")
	if err := pbq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProductBrands, *ProductBrandsQuery]()
	return withInterceptors[[]*ProductBrands](ctx, pbq, qr, pbq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pbq *ProductBrandsQuery) AllX(ctx context.Context) []*ProductBrands {
	nodes, err := pbq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProductBrands IDs.
func (pbq *ProductBrandsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pbq.ctx.Unique == nil && pbq.path != nil {
		pbq.Unique(true)
	}
	ctx = setContextOp(ctx, pbq.ctx, "IDs")
	if err = pbq.Select(productbrands.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pbq *ProductBrandsQuery) IDsX(ctx context.Context) []int {
	ids, err := pbq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pbq *ProductBrandsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pbq.ctx, "Count")
	if err := pbq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pbq, querierCount[*ProductBrandsQuery](), pbq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pbq *ProductBrandsQuery) CountX(ctx context.Context) int {
	count, err := pbq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pbq *ProductBrandsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pbq.ctx, "Exist")
	switch _, err := pbq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pbq *ProductBrandsQuery) ExistX(ctx context.Context) bool {
	exist, err := pbq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductBrandsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pbq *ProductBrandsQuery) Clone() *ProductBrandsQuery {
	if pbq == nil {
		return nil
	}
	return &ProductBrandsQuery{
		config:     pbq.config,
		ctx:        pbq.ctx.Clone(),
		order:      append([]productbrands.OrderOption{}, pbq.order...),
		inters:     append([]Interceptor{}, pbq.inters...),
		predicates: append([]predicate.ProductBrands{}, pbq.predicates...),
		// clone intermediate query.
		sql:  pbq.sql.Clone(),
		path: pbq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProductBrands.Query().
//		GroupBy(productbrands.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pbq *ProductBrandsQuery) GroupBy(field string, fields ...string) *ProductBrandsGroupBy {
	pbq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProductBrandsGroupBy{build: pbq}
	grbuild.flds = &pbq.ctx.Fields
	grbuild.label = productbrands.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ProductBrands.Query().
//		Select(productbrands.FieldName).
//		Scan(ctx, &v)
func (pbq *ProductBrandsQuery) Select(fields ...string) *ProductBrandsSelect {
	pbq.ctx.Fields = append(pbq.ctx.Fields, fields...)
	sbuild := &ProductBrandsSelect{ProductBrandsQuery: pbq}
	sbuild.label = productbrands.Label
	sbuild.flds, sbuild.scan = &pbq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProductBrandsSelect configured with the given aggregations.
func (pbq *ProductBrandsQuery) Aggregate(fns ...AggregateFunc) *ProductBrandsSelect {
	return pbq.Select().Aggregate(fns...)
}

func (pbq *ProductBrandsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pbq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pbq); err != nil {
				return err
			}
		}
	}
	for _, f := range pbq.ctx.Fields {
		if !productbrands.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pbq.path != nil {
		prev, err := pbq.path(ctx)
		if err != nil {
			return err
		}
		pbq.sql = prev
	}
	return nil
}

func (pbq *ProductBrandsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProductBrands, error) {
	var (
		nodes = []*ProductBrands{}
		_spec = pbq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProductBrands).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProductBrands{config: pbq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pbq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pbq *ProductBrandsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pbq.querySpec()
	_spec.Node.Columns = pbq.ctx.Fields
	if len(pbq.ctx.Fields) > 0 {
		_spec.Unique = pbq.ctx.Unique != nil && *pbq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pbq.driver, _spec)
}

func (pbq *ProductBrandsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(productbrands.Table, productbrands.Columns, sqlgraph.NewFieldSpec(productbrands.FieldID, field.TypeInt))
	_spec.From = pbq.sql
	if unique := pbq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pbq.path != nil {
		_spec.Unique = true
	}
	if fields := pbq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productbrands.FieldID)
		for i := range fields {
			if fields[i] != productbrands.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pbq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pbq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pbq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pbq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pbq *ProductBrandsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pbq.driver.Dialect())
	t1 := builder.Table(productbrands.Table)
	columns := pbq.ctx.Fields
	if len(columns) == 0 {
		columns = productbrands.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pbq.sql != nil {
		selector = pbq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pbq.ctx.Unique != nil && *pbq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pbq.predicates {
		p(selector)
	}
	for _, p := range pbq.order {
		p(selector)
	}
	if offset := pbq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pbq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProductBrandsGroupBy is the group-by builder for ProductBrands entities.
type ProductBrandsGroupBy struct {
	selector
	build *ProductBrandsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pbgb *ProductBrandsGroupBy) Aggregate(fns ...AggregateFunc) *ProductBrandsGroupBy {
	pbgb.fns = append(pbgb.fns, fns...)
	return pbgb
}

// Scan applies the selector query and scans the result into the given value.
func (pbgb *ProductBrandsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pbgb.build.ctx, "GroupBy")
	if err := pbgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductBrandsQuery, *ProductBrandsGroupBy](ctx, pbgb.build, pbgb, pbgb.build.inters, v)
}

func (pbgb *ProductBrandsGroupBy) sqlScan(ctx context.Context, root *ProductBrandsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pbgb.fns))
	for _, fn := range pbgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pbgb.flds)+len(pbgb.fns))
		for _, f := range *pbgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pbgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pbgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProductBrandsSelect is the builder for selecting fields of ProductBrands entities.
type ProductBrandsSelect struct {
	*ProductBrandsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pbs *ProductBrandsSelect) Aggregate(fns ...AggregateFunc) *ProductBrandsSelect {
	pbs.fns = append(pbs.fns, fns...)
	return pbs
}

// Scan applies the selector query and scans the result into the given value.
func (pbs *ProductBrandsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pbs.ctx, "Select")
	if err := pbs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductBrandsQuery, *ProductBrandsSelect](ctx, pbs.ProductBrandsQuery, pbs, pbs.inters, v)
}

func (pbs *ProductBrandsSelect) sqlScan(ctx context.Context, root *ProductBrandsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pbs.fns))
	for _, fn := range pbs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pbs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pbs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
