// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Shipment is an object representing the database table.
type Shipment struct {
	ID            null.Int64  `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
	OrderID       null.Int64  `boil:"order_id" json:"order_id,omitempty" toml:"order_id" yaml:"order_id,omitempty"`
	OrderDetailID null.Int64  `boil:"order_detail_id" json:"order_detail_id,omitempty" toml:"order_detail_id" yaml:"order_detail_id,omitempty"`
	ShipmentDate  null.String `boil:"shipment_date" json:"shipment_date,omitempty" toml:"shipment_date" yaml:"shipment_date,omitempty"`
	CreatedAt     null.String `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt     null.String `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *shipmentR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L shipmentL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ShipmentColumns = struct {
	ID            string
	OrderID       string
	OrderDetailID string
	ShipmentDate  string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "id",
	OrderID:       "order_id",
	OrderDetailID: "order_detail_id",
	ShipmentDate:  "shipment_date",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

var ShipmentTableColumns = struct {
	ID            string
	OrderID       string
	OrderDetailID string
	ShipmentDate  string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "shipments.id",
	OrderID:       "shipments.order_id",
	OrderDetailID: "shipments.order_detail_id",
	ShipmentDate:  "shipments.shipment_date",
	CreatedAt:     "shipments.created_at",
	UpdatedAt:     "shipments.updated_at",
}

// Generated where

var ShipmentWhere = struct {
	ID            whereHelpernull_Int64
	OrderID       whereHelpernull_Int64
	OrderDetailID whereHelpernull_Int64
	ShipmentDate  whereHelpernull_String
	CreatedAt     whereHelpernull_String
	UpdatedAt     whereHelpernull_String
}{
	ID:            whereHelpernull_Int64{field: "\"shipments\".\"id\""},
	OrderID:       whereHelpernull_Int64{field: "\"shipments\".\"order_id\""},
	OrderDetailID: whereHelpernull_Int64{field: "\"shipments\".\"order_detail_id\""},
	ShipmentDate:  whereHelpernull_String{field: "\"shipments\".\"shipment_date\""},
	CreatedAt:     whereHelpernull_String{field: "\"shipments\".\"created_at\""},
	UpdatedAt:     whereHelpernull_String{field: "\"shipments\".\"updated_at\""},
}

// ShipmentRels is where relationship names are stored.
var ShipmentRels = struct {
	OrderDetail string
	Order       string
}{
	OrderDetail: "OrderDetail",
	Order:       "Order",
}

// shipmentR is where relationships are stored.
type shipmentR struct {
	OrderDetail *OrderDetail `boil:"OrderDetail" json:"OrderDetail" toml:"OrderDetail" yaml:"OrderDetail"`
	Order       *Order       `boil:"Order" json:"Order" toml:"Order" yaml:"Order"`
}

// NewStruct creates a new relationship struct
func (*shipmentR) NewStruct() *shipmentR {
	return &shipmentR{}
}

func (r *shipmentR) GetOrderDetail() *OrderDetail {
	if r == nil {
		return nil
	}
	return r.OrderDetail
}

func (r *shipmentR) GetOrder() *Order {
	if r == nil {
		return nil
	}
	return r.Order
}

// shipmentL is where Load methods for each relationship are stored.
type shipmentL struct{}

var (
	shipmentAllColumns            = []string{"id", "order_id", "order_detail_id", "shipment_date", "created_at", "updated_at"}
	shipmentColumnsWithoutDefault = []string{}
	shipmentColumnsWithDefault    = []string{"id", "order_id", "order_detail_id", "shipment_date", "created_at", "updated_at"}
	shipmentPrimaryKeyColumns     = []string{"id"}
	shipmentGeneratedColumns      = []string{}
)

type (
	// ShipmentSlice is an alias for a slice of pointers to Shipment.
	// This should almost always be used instead of []Shipment.
	ShipmentSlice []*Shipment
	// ShipmentHook is the signature for custom Shipment hook methods
	ShipmentHook func(context.Context, boil.ContextExecutor, *Shipment) error

	shipmentQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	shipmentType                 = reflect.TypeOf(&Shipment{})
	shipmentMapping              = queries.MakeStructMapping(shipmentType)
	shipmentPrimaryKeyMapping, _ = queries.BindMapping(shipmentType, shipmentMapping, shipmentPrimaryKeyColumns)
	shipmentInsertCacheMut       sync.RWMutex
	shipmentInsertCache          = make(map[string]insertCache)
	shipmentUpdateCacheMut       sync.RWMutex
	shipmentUpdateCache          = make(map[string]updateCache)
	shipmentUpsertCacheMut       sync.RWMutex
	shipmentUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var shipmentAfterSelectHooks []ShipmentHook

var shipmentBeforeInsertHooks []ShipmentHook
var shipmentAfterInsertHooks []ShipmentHook

var shipmentBeforeUpdateHooks []ShipmentHook
var shipmentAfterUpdateHooks []ShipmentHook

var shipmentBeforeDeleteHooks []ShipmentHook
var shipmentAfterDeleteHooks []ShipmentHook

var shipmentBeforeUpsertHooks []ShipmentHook
var shipmentAfterUpsertHooks []ShipmentHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Shipment) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shipmentAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Shipment) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shipmentBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Shipment) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shipmentAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Shipment) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shipmentBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Shipment) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shipmentAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Shipment) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shipmentBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Shipment) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shipmentAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Shipment) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shipmentBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Shipment) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shipmentAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddShipmentHook registers your hook function for all future operations.
func AddShipmentHook(hookPoint boil.HookPoint, shipmentHook ShipmentHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		shipmentAfterSelectHooks = append(shipmentAfterSelectHooks, shipmentHook)
	case boil.BeforeInsertHook:
		shipmentBeforeInsertHooks = append(shipmentBeforeInsertHooks, shipmentHook)
	case boil.AfterInsertHook:
		shipmentAfterInsertHooks = append(shipmentAfterInsertHooks, shipmentHook)
	case boil.BeforeUpdateHook:
		shipmentBeforeUpdateHooks = append(shipmentBeforeUpdateHooks, shipmentHook)
	case boil.AfterUpdateHook:
		shipmentAfterUpdateHooks = append(shipmentAfterUpdateHooks, shipmentHook)
	case boil.BeforeDeleteHook:
		shipmentBeforeDeleteHooks = append(shipmentBeforeDeleteHooks, shipmentHook)
	case boil.AfterDeleteHook:
		shipmentAfterDeleteHooks = append(shipmentAfterDeleteHooks, shipmentHook)
	case boil.BeforeUpsertHook:
		shipmentBeforeUpsertHooks = append(shipmentBeforeUpsertHooks, shipmentHook)
	case boil.AfterUpsertHook:
		shipmentAfterUpsertHooks = append(shipmentAfterUpsertHooks, shipmentHook)
	}
}

// One returns a single shipment record from the query.
func (q shipmentQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Shipment, error) {
	o := &Shipment{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: failed to execute a one query for shipments")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Shipment records from the query.
func (q shipmentQuery) All(ctx context.Context, exec boil.ContextExecutor) (ShipmentSlice, error) {
	var o []*Shipment

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "db: failed to assign all query results to Shipment slice")
	}

	if len(shipmentAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Shipment records in the query.
func (q shipmentQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to count shipments rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q shipmentQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "db: failed to check if shipments exists")
	}

	return count > 0, nil
}

// OrderDetail pointed to by the foreign key.
func (o *Shipment) OrderDetail(mods ...qm.QueryMod) orderDetailQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.OrderDetailID),
	}

	queryMods = append(queryMods, mods...)

	return OrderDetails(queryMods...)
}

// Order pointed to by the foreign key.
func (o *Shipment) Order(mods ...qm.QueryMod) orderQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.OrderID),
	}

	queryMods = append(queryMods, mods...)

	return Orders(queryMods...)
}

// LoadOrderDetail allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (shipmentL) LoadOrderDetail(ctx context.Context, e boil.ContextExecutor, singular bool, maybeShipment interface{}, mods queries.Applicator) error {
	var slice []*Shipment
	var object *Shipment

	if singular {
		var ok bool
		object, ok = maybeShipment.(*Shipment)
		if !ok {
			object = new(Shipment)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeShipment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeShipment))
			}
		}
	} else {
		s, ok := maybeShipment.(*[]*Shipment)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeShipment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeShipment))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &shipmentR{}
		}
		if !queries.IsNil(object.OrderDetailID) {
			args = append(args, object.OrderDetailID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &shipmentR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.OrderDetailID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.OrderDetailID) {
				args = append(args, obj.OrderDetailID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`order_details`),
		qm.WhereIn(`order_details.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load OrderDetail")
	}

	var resultSlice []*OrderDetail
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice OrderDetail")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for order_details")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for order_details")
	}

	if len(orderDetailAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.OrderDetail = foreign
		if foreign.R == nil {
			foreign.R = &orderDetailR{}
		}
		foreign.R.Shipments = append(foreign.R.Shipments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.OrderDetailID, foreign.ID) {
				local.R.OrderDetail = foreign
				if foreign.R == nil {
					foreign.R = &orderDetailR{}
				}
				foreign.R.Shipments = append(foreign.R.Shipments, local)
				break
			}
		}
	}

	return nil
}

// LoadOrder allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (shipmentL) LoadOrder(ctx context.Context, e boil.ContextExecutor, singular bool, maybeShipment interface{}, mods queries.Applicator) error {
	var slice []*Shipment
	var object *Shipment

	if singular {
		var ok bool
		object, ok = maybeShipment.(*Shipment)
		if !ok {
			object = new(Shipment)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeShipment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeShipment))
			}
		}
	} else {
		s, ok := maybeShipment.(*[]*Shipment)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeShipment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeShipment))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &shipmentR{}
		}
		if !queries.IsNil(object.OrderID) {
			args = append(args, object.OrderID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &shipmentR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.OrderID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.OrderID) {
				args = append(args, obj.OrderID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`orders`),
		qm.WhereIn(`orders.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Order")
	}

	var resultSlice []*Order
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Order")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for orders")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for orders")
	}

	if len(orderAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Order = foreign
		if foreign.R == nil {
			foreign.R = &orderR{}
		}
		foreign.R.Shipments = append(foreign.R.Shipments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.OrderID, foreign.ID) {
				local.R.Order = foreign
				if foreign.R == nil {
					foreign.R = &orderR{}
				}
				foreign.R.Shipments = append(foreign.R.Shipments, local)
				break
			}
		}
	}

	return nil
}

// SetOrderDetail of the shipment to the related item.
// Sets o.R.OrderDetail to related.
// Adds o to related.R.Shipments.
func (o *Shipment) SetOrderDetail(ctx context.Context, exec boil.ContextExecutor, insert bool, related *OrderDetail) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"shipments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"order_detail_id"}),
		strmangle.WhereClause("\"", "\"", 0, shipmentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.OrderDetailID, related.ID)
	if o.R == nil {
		o.R = &shipmentR{
			OrderDetail: related,
		}
	} else {
		o.R.OrderDetail = related
	}

	if related.R == nil {
		related.R = &orderDetailR{
			Shipments: ShipmentSlice{o},
		}
	} else {
		related.R.Shipments = append(related.R.Shipments, o)
	}

	return nil
}

// RemoveOrderDetail relationship.
// Sets o.R.OrderDetail to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Shipment) RemoveOrderDetail(ctx context.Context, exec boil.ContextExecutor, related *OrderDetail) error {
	var err error

	queries.SetScanner(&o.OrderDetailID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("order_detail_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.OrderDetail = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Shipments {
		if queries.Equal(o.OrderDetailID, ri.OrderDetailID) {
			continue
		}

		ln := len(related.R.Shipments)
		if ln > 1 && i < ln-1 {
			related.R.Shipments[i] = related.R.Shipments[ln-1]
		}
		related.R.Shipments = related.R.Shipments[:ln-1]
		break
	}
	return nil
}

// SetOrder of the shipment to the related item.
// Sets o.R.Order to related.
// Adds o to related.R.Shipments.
func (o *Shipment) SetOrder(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Order) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"shipments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"order_id"}),
		strmangle.WhereClause("\"", "\"", 0, shipmentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.OrderID, related.ID)
	if o.R == nil {
		o.R = &shipmentR{
			Order: related,
		}
	} else {
		o.R.Order = related
	}

	if related.R == nil {
		related.R = &orderR{
			Shipments: ShipmentSlice{o},
		}
	} else {
		related.R.Shipments = append(related.R.Shipments, o)
	}

	return nil
}

// RemoveOrder relationship.
// Sets o.R.Order to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Shipment) RemoveOrder(ctx context.Context, exec boil.ContextExecutor, related *Order) error {
	var err error

	queries.SetScanner(&o.OrderID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("order_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Order = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Shipments {
		if queries.Equal(o.OrderID, ri.OrderID) {
			continue
		}

		ln := len(related.R.Shipments)
		if ln > 1 && i < ln-1 {
			related.R.Shipments[i] = related.R.Shipments[ln-1]
		}
		related.R.Shipments = related.R.Shipments[:ln-1]
		break
	}
	return nil
}

// Shipments retrieves all the records using an executor.
func Shipments(mods ...qm.QueryMod) shipmentQuery {
	mods = append(mods, qm.From("\"shipments\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"shipments\".*"})
	}

	return shipmentQuery{q}
}

// FindShipment retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindShipment(ctx context.Context, exec boil.ContextExecutor, iD null.Int64, selectCols ...string) (*Shipment, error) {
	shipmentObj := &Shipment{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"shipments\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, shipmentObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: unable to select from shipments")
	}

	if err = shipmentObj.doAfterSelectHooks(ctx, exec); err != nil {
		return shipmentObj, err
	}

	return shipmentObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Shipment) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("db: no shipments provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(shipmentColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	shipmentInsertCacheMut.RLock()
	cache, cached := shipmentInsertCache[key]
	shipmentInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			shipmentAllColumns,
			shipmentColumnsWithDefault,
			shipmentColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(shipmentType, shipmentMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(shipmentType, shipmentMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"shipments\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"shipments\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "db: unable to insert into shipments")
	}

	if !cached {
		shipmentInsertCacheMut.Lock()
		shipmentInsertCache[key] = cache
		shipmentInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Shipment.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Shipment) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	shipmentUpdateCacheMut.RLock()
	cache, cached := shipmentUpdateCache[key]
	shipmentUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			shipmentAllColumns,
			shipmentPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("db: unable to update shipments, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"shipments\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, shipmentPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(shipmentType, shipmentMapping, append(wl, shipmentPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update shipments row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by update for shipments")
	}

	if !cached {
		shipmentUpdateCacheMut.Lock()
		shipmentUpdateCache[key] = cache
		shipmentUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q shipmentQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all for shipments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected for shipments")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ShipmentSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("db: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), shipmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"shipments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, shipmentPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all in shipment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected all in update all shipment")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Shipment) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("db: no shipments provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(shipmentColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	shipmentUpsertCacheMut.RLock()
	cache, cached := shipmentUpsertCache[key]
	shipmentUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			shipmentAllColumns,
			shipmentColumnsWithDefault,
			shipmentColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			shipmentAllColumns,
			shipmentPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("db: unable to upsert shipments, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(shipmentPrimaryKeyColumns))
			copy(conflict, shipmentPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"shipments\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(shipmentType, shipmentMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(shipmentType, shipmentMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "db: unable to upsert shipments")
	}

	if !cached {
		shipmentUpsertCacheMut.Lock()
		shipmentUpsertCache[key] = cache
		shipmentUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Shipment record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Shipment) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("db: no Shipment provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), shipmentPrimaryKeyMapping)
	sql := "DELETE FROM \"shipments\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete from shipments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by delete for shipments")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q shipmentQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("db: no shipmentQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from shipments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for shipments")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ShipmentSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(shipmentBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), shipmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"shipments\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, shipmentPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from shipment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for shipments")
	}

	if len(shipmentAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Shipment) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindShipment(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ShipmentSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ShipmentSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), shipmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"shipments\".* FROM \"shipments\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, shipmentPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "db: unable to reload all in ShipmentSlice")
	}

	*o = slice

	return nil
}

// ShipmentExists checks if the Shipment row exists.
func ShipmentExists(ctx context.Context, exec boil.ContextExecutor, iD null.Int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"shipments\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "db: unable to check if shipments exists")
	}

	return exists, nil
}

// Exists checks if the Shipment row exists.
func (o *Shipment) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ShipmentExists(ctx, exec, o.ID)
}
