// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// UserFavorite is an object representing the database table.
type UserFavorite struct {
	ID             null.Int64  `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
	UserID         null.Int64  `boil:"user_id" json:"user_id,omitempty" toml:"user_id" yaml:"user_id,omitempty"`
	ProductStockID null.Int64  `boil:"product_stock_id" json:"product_stock_id,omitempty" toml:"product_stock_id" yaml:"product_stock_id,omitempty"`
	CreatedAt      null.String `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt      null.String `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *userFavoriteR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userFavoriteL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserFavoriteColumns = struct {
	ID             string
	UserID         string
	ProductStockID string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "id",
	UserID:         "user_id",
	ProductStockID: "product_stock_id",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

var UserFavoriteTableColumns = struct {
	ID             string
	UserID         string
	ProductStockID string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "user_favorites.id",
	UserID:         "user_favorites.user_id",
	ProductStockID: "user_favorites.product_stock_id",
	CreatedAt:      "user_favorites.created_at",
	UpdatedAt:      "user_favorites.updated_at",
}

// Generated where

var UserFavoriteWhere = struct {
	ID             whereHelpernull_Int64
	UserID         whereHelpernull_Int64
	ProductStockID whereHelpernull_Int64
	CreatedAt      whereHelpernull_String
	UpdatedAt      whereHelpernull_String
}{
	ID:             whereHelpernull_Int64{field: "\"user_favorites\".\"id\""},
	UserID:         whereHelpernull_Int64{field: "\"user_favorites\".\"user_id\""},
	ProductStockID: whereHelpernull_Int64{field: "\"user_favorites\".\"product_stock_id\""},
	CreatedAt:      whereHelpernull_String{field: "\"user_favorites\".\"created_at\""},
	UpdatedAt:      whereHelpernull_String{field: "\"user_favorites\".\"updated_at\""},
}

// UserFavoriteRels is where relationship names are stored.
var UserFavoriteRels = struct {
	ProductStock string
	User         string
}{
	ProductStock: "ProductStock",
	User:         "User",
}

// userFavoriteR is where relationships are stored.
type userFavoriteR struct {
	ProductStock *ProductStock `boil:"ProductStock" json:"ProductStock" toml:"ProductStock" yaml:"ProductStock"`
	User         *User         `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*userFavoriteR) NewStruct() *userFavoriteR {
	return &userFavoriteR{}
}

func (r *userFavoriteR) GetProductStock() *ProductStock {
	if r == nil {
		return nil
	}
	return r.ProductStock
}

func (r *userFavoriteR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// userFavoriteL is where Load methods for each relationship are stored.
type userFavoriteL struct{}

var (
	userFavoriteAllColumns            = []string{"id", "user_id", "product_stock_id", "created_at", "updated_at"}
	userFavoriteColumnsWithoutDefault = []string{}
	userFavoriteColumnsWithDefault    = []string{"id", "user_id", "product_stock_id", "created_at", "updated_at"}
	userFavoritePrimaryKeyColumns     = []string{"id"}
	userFavoriteGeneratedColumns      = []string{}
)

type (
	// UserFavoriteSlice is an alias for a slice of pointers to UserFavorite.
	// This should almost always be used instead of []UserFavorite.
	UserFavoriteSlice []*UserFavorite
	// UserFavoriteHook is the signature for custom UserFavorite hook methods
	UserFavoriteHook func(context.Context, boil.ContextExecutor, *UserFavorite) error

	userFavoriteQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userFavoriteType                 = reflect.TypeOf(&UserFavorite{})
	userFavoriteMapping              = queries.MakeStructMapping(userFavoriteType)
	userFavoritePrimaryKeyMapping, _ = queries.BindMapping(userFavoriteType, userFavoriteMapping, userFavoritePrimaryKeyColumns)
	userFavoriteInsertCacheMut       sync.RWMutex
	userFavoriteInsertCache          = make(map[string]insertCache)
	userFavoriteUpdateCacheMut       sync.RWMutex
	userFavoriteUpdateCache          = make(map[string]updateCache)
	userFavoriteUpsertCacheMut       sync.RWMutex
	userFavoriteUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userFavoriteAfterSelectHooks []UserFavoriteHook

var userFavoriteBeforeInsertHooks []UserFavoriteHook
var userFavoriteAfterInsertHooks []UserFavoriteHook

var userFavoriteBeforeUpdateHooks []UserFavoriteHook
var userFavoriteAfterUpdateHooks []UserFavoriteHook

var userFavoriteBeforeDeleteHooks []UserFavoriteHook
var userFavoriteAfterDeleteHooks []UserFavoriteHook

var userFavoriteBeforeUpsertHooks []UserFavoriteHook
var userFavoriteAfterUpsertHooks []UserFavoriteHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserFavorite) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoriteAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserFavorite) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoriteBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserFavorite) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoriteAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserFavorite) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoriteBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserFavorite) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoriteAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserFavorite) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoriteBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserFavorite) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoriteAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserFavorite) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoriteBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserFavorite) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoriteAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserFavoriteHook registers your hook function for all future operations.
func AddUserFavoriteHook(hookPoint boil.HookPoint, userFavoriteHook UserFavoriteHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userFavoriteAfterSelectHooks = append(userFavoriteAfterSelectHooks, userFavoriteHook)
	case boil.BeforeInsertHook:
		userFavoriteBeforeInsertHooks = append(userFavoriteBeforeInsertHooks, userFavoriteHook)
	case boil.AfterInsertHook:
		userFavoriteAfterInsertHooks = append(userFavoriteAfterInsertHooks, userFavoriteHook)
	case boil.BeforeUpdateHook:
		userFavoriteBeforeUpdateHooks = append(userFavoriteBeforeUpdateHooks, userFavoriteHook)
	case boil.AfterUpdateHook:
		userFavoriteAfterUpdateHooks = append(userFavoriteAfterUpdateHooks, userFavoriteHook)
	case boil.BeforeDeleteHook:
		userFavoriteBeforeDeleteHooks = append(userFavoriteBeforeDeleteHooks, userFavoriteHook)
	case boil.AfterDeleteHook:
		userFavoriteAfterDeleteHooks = append(userFavoriteAfterDeleteHooks, userFavoriteHook)
	case boil.BeforeUpsertHook:
		userFavoriteBeforeUpsertHooks = append(userFavoriteBeforeUpsertHooks, userFavoriteHook)
	case boil.AfterUpsertHook:
		userFavoriteAfterUpsertHooks = append(userFavoriteAfterUpsertHooks, userFavoriteHook)
	}
}

// One returns a single userFavorite record from the query.
func (q userFavoriteQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserFavorite, error) {
	o := &UserFavorite{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: failed to execute a one query for user_favorites")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserFavorite records from the query.
func (q userFavoriteQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserFavoriteSlice, error) {
	var o []*UserFavorite

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "db: failed to assign all query results to UserFavorite slice")
	}

	if len(userFavoriteAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserFavorite records in the query.
func (q userFavoriteQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to count user_favorites rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userFavoriteQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "db: failed to check if user_favorites exists")
	}

	return count > 0, nil
}

// ProductStock pointed to by the foreign key.
func (o *UserFavorite) ProductStock(mods ...qm.QueryMod) productStockQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ProductStockID),
	}

	queryMods = append(queryMods, mods...)

	return ProductStocks(queryMods...)
}

// User pointed to by the foreign key.
func (o *UserFavorite) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadProductStock allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userFavoriteL) LoadProductStock(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserFavorite interface{}, mods queries.Applicator) error {
	var slice []*UserFavorite
	var object *UserFavorite

	if singular {
		var ok bool
		object, ok = maybeUserFavorite.(*UserFavorite)
		if !ok {
			object = new(UserFavorite)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserFavorite)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserFavorite))
			}
		}
	} else {
		s, ok := maybeUserFavorite.(*[]*UserFavorite)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserFavorite)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserFavorite))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userFavoriteR{}
		}
		if !queries.IsNil(object.ProductStockID) {
			args = append(args, object.ProductStockID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userFavoriteR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ProductStockID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.ProductStockID) {
				args = append(args, obj.ProductStockID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`product_stocks`),
		qm.WhereIn(`product_stocks.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ProductStock")
	}

	var resultSlice []*ProductStock
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ProductStock")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for product_stocks")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for product_stocks")
	}

	if len(productStockAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ProductStock = foreign
		if foreign.R == nil {
			foreign.R = &productStockR{}
		}
		foreign.R.UserFavorites = append(foreign.R.UserFavorites, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ProductStockID, foreign.ID) {
				local.R.ProductStock = foreign
				if foreign.R == nil {
					foreign.R = &productStockR{}
				}
				foreign.R.UserFavorites = append(foreign.R.UserFavorites, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userFavoriteL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserFavorite interface{}, mods queries.Applicator) error {
	var slice []*UserFavorite
	var object *UserFavorite

	if singular {
		var ok bool
		object, ok = maybeUserFavorite.(*UserFavorite)
		if !ok {
			object = new(UserFavorite)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserFavorite)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserFavorite))
			}
		}
	} else {
		s, ok := maybeUserFavorite.(*[]*UserFavorite)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserFavorite)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserFavorite))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userFavoriteR{}
		}
		if !queries.IsNil(object.UserID) {
			args = append(args, object.UserID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userFavoriteR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.UserID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.UserID) {
				args = append(args, obj.UserID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserFavorites = append(foreign.R.UserFavorites, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UserID, foreign.ID) {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserFavorites = append(foreign.R.UserFavorites, local)
				break
			}
		}
	}

	return nil
}

// SetProductStock of the userFavorite to the related item.
// Sets o.R.ProductStock to related.
// Adds o to related.R.UserFavorites.
func (o *UserFavorite) SetProductStock(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ProductStock) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_favorites\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"product_stock_id"}),
		strmangle.WhereClause("\"", "\"", 0, userFavoritePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ProductStockID, related.ID)
	if o.R == nil {
		o.R = &userFavoriteR{
			ProductStock: related,
		}
	} else {
		o.R.ProductStock = related
	}

	if related.R == nil {
		related.R = &productStockR{
			UserFavorites: UserFavoriteSlice{o},
		}
	} else {
		related.R.UserFavorites = append(related.R.UserFavorites, o)
	}

	return nil
}

// RemoveProductStock relationship.
// Sets o.R.ProductStock to nil.
// Removes o from all passed in related items' relationships struct.
func (o *UserFavorite) RemoveProductStock(ctx context.Context, exec boil.ContextExecutor, related *ProductStock) error {
	var err error

	queries.SetScanner(&o.ProductStockID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("product_stock_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.ProductStock = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.UserFavorites {
		if queries.Equal(o.ProductStockID, ri.ProductStockID) {
			continue
		}

		ln := len(related.R.UserFavorites)
		if ln > 1 && i < ln-1 {
			related.R.UserFavorites[i] = related.R.UserFavorites[ln-1]
		}
		related.R.UserFavorites = related.R.UserFavorites[:ln-1]
		break
	}
	return nil
}

// SetUser of the userFavorite to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserFavorites.
func (o *UserFavorite) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_favorites\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 0, userFavoritePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UserID, related.ID)
	if o.R == nil {
		o.R = &userFavoriteR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserFavorites: UserFavoriteSlice{o},
		}
	} else {
		related.R.UserFavorites = append(related.R.UserFavorites, o)
	}

	return nil
}

// RemoveUser relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct.
func (o *UserFavorite) RemoveUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.UserID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("user_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.User = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.UserFavorites {
		if queries.Equal(o.UserID, ri.UserID) {
			continue
		}

		ln := len(related.R.UserFavorites)
		if ln > 1 && i < ln-1 {
			related.R.UserFavorites[i] = related.R.UserFavorites[ln-1]
		}
		related.R.UserFavorites = related.R.UserFavorites[:ln-1]
		break
	}
	return nil
}

// UserFavorites retrieves all the records using an executor.
func UserFavorites(mods ...qm.QueryMod) userFavoriteQuery {
	mods = append(mods, qm.From("\"user_favorites\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_favorites\".*"})
	}

	return userFavoriteQuery{q}
}

// FindUserFavorite retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserFavorite(ctx context.Context, exec boil.ContextExecutor, iD null.Int64, selectCols ...string) (*UserFavorite, error) {
	userFavoriteObj := &UserFavorite{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_favorites\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userFavoriteObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: unable to select from user_favorites")
	}

	if err = userFavoriteObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userFavoriteObj, err
	}

	return userFavoriteObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserFavorite) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("db: no user_favorites provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userFavoriteColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userFavoriteInsertCacheMut.RLock()
	cache, cached := userFavoriteInsertCache[key]
	userFavoriteInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userFavoriteAllColumns,
			userFavoriteColumnsWithDefault,
			userFavoriteColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userFavoriteType, userFavoriteMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userFavoriteType, userFavoriteMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_favorites\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_favorites\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "db: unable to insert into user_favorites")
	}

	if !cached {
		userFavoriteInsertCacheMut.Lock()
		userFavoriteInsertCache[key] = cache
		userFavoriteInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserFavorite.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserFavorite) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userFavoriteUpdateCacheMut.RLock()
	cache, cached := userFavoriteUpdateCache[key]
	userFavoriteUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userFavoriteAllColumns,
			userFavoritePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("db: unable to update user_favorites, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_favorites\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, userFavoritePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userFavoriteType, userFavoriteMapping, append(wl, userFavoritePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update user_favorites row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by update for user_favorites")
	}

	if !cached {
		userFavoriteUpdateCacheMut.Lock()
		userFavoriteUpdateCache[key] = cache
		userFavoriteUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userFavoriteQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all for user_favorites")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected for user_favorites")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserFavoriteSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("db: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userFavoritePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_favorites\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userFavoritePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all in userFavorite slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected all in update all userFavorite")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserFavorite) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("db: no user_favorites provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userFavoriteColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userFavoriteUpsertCacheMut.RLock()
	cache, cached := userFavoriteUpsertCache[key]
	userFavoriteUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			userFavoriteAllColumns,
			userFavoriteColumnsWithDefault,
			userFavoriteColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			userFavoriteAllColumns,
			userFavoritePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("db: unable to upsert user_favorites, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(userFavoritePrimaryKeyColumns))
			copy(conflict, userFavoritePrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"user_favorites\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(userFavoriteType, userFavoriteMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userFavoriteType, userFavoriteMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "db: unable to upsert user_favorites")
	}

	if !cached {
		userFavoriteUpsertCacheMut.Lock()
		userFavoriteUpsertCache[key] = cache
		userFavoriteUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserFavorite record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserFavorite) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("db: no UserFavorite provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userFavoritePrimaryKeyMapping)
	sql := "DELETE FROM \"user_favorites\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete from user_favorites")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by delete for user_favorites")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userFavoriteQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("db: no userFavoriteQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from user_favorites")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for user_favorites")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserFavoriteSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userFavoriteBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userFavoritePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_favorites\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userFavoritePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from userFavorite slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for user_favorites")
	}

	if len(userFavoriteAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserFavorite) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserFavorite(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserFavoriteSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserFavoriteSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userFavoritePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_favorites\".* FROM \"user_favorites\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userFavoritePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "db: unable to reload all in UserFavoriteSlice")
	}

	*o = slice

	return nil
}

// UserFavoriteExists checks if the UserFavorite row exists.
func UserFavoriteExists(ctx context.Context, exec boil.ContextExecutor, iD null.Int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_favorites\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "db: unable to check if user_favorites exists")
	}

	return exists, nil
}

// Exists checks if the UserFavorite row exists.
func (o *UserFavorite) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserFavoriteExists(ctx, exec, o.ID)
}
